-- 模板生成脚本[T_PUB_TEMPLET_1_ITEM_GROUP]
-- ================start===========================================================
-- 删除模板明细数据
delete pub_templet_1_item where pk_pub_templet_1 in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_PUB_TEMPLET_1_ITEM_GROUP');
-- 删除模板分组信息
delete from PUB_TEMPLET_1_ITEM_GROUP where templetid in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_PUB_TEMPLET_1_ITEM_GROUP');
-- 判断是否已经存在模板
DECLARE TEMPL_COUNT NUMBER(6);
BEGIN
  SELECT COUNT(*) INTO TEMPL_COUNT FROM pub_templet_1 where templetcode ='T_PUB_TEMPLET_1_ITEM_GROUP';
  IF TEMPL_COUNT > 0 THEN
    -- 更新老的模板，ID没有变化
    UPDATE PUB_TEMPLET_1 SET  templetcode='T_PUB_TEMPLET_1_ITEM_GROUP', templetname='元原模板项分组', tablename='PUB_TEMPLET_1_ITEM_GROUP', datasourcename='datasource_default', pkname='ID', pksequencename='S_PUB_TEMPLET_1_ITEM_GROUP', savedtablename='PUB_TEMPLET_1_ITEM_GROUP', cardcustpanel='SMARTX', listcustpanel=null, dataconstraint=null, parent_pub_template=null, comefrom='0', ordersetting=null WHERE templetcode = 'T_PUB_TEMPLET_1_ITEM_GROUP';
  ELSE
    -- 插入新模板，新生成ID
    Insert Into PUB_TEMPLET_1 (pk_pub_templet_1, templetcode, templetname, tablename, datasourcename, pkname, pksequencename, savedtablename, cardcustpanel, listcustpanel, dataconstraint, parent_pub_template, comefrom, ordersetting) values (s_pub_templet_1.nextval, 'T_PUB_TEMPLET_1_ITEM_GROUP', '元原模板项分组', 'PUB_TEMPLET_1_ITEM_GROUP', 'datasource_default', 'ID', 'S_PUB_TEMPLET_1_ITEM_GROUP', 'PUB_TEMPLET_1_ITEM_GROUP', 'SMARTX', null, null, null, '0', null);
  END IF;
  -- 插入模板分组
 -- 插入模板明细
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM_GROUP'), 'ID', 'ID', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '1', '145', '150', 'Y', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM_GROUP'), 'NAME', '名称', '文本框', null, null, 'Y', '2', 'Y', null, null, null, null, '2', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM_GROUP'), 'ISSHOW', '是否显示', '下拉框', 'select ''Y'' value,1 code,''是'' name from dual
 union
 select ''N'' value,1 code,''否'' name from dual', null, 'Y', '2', 'Y', null, null, '"Y"', null, '4', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM_GROUP'), 'ISEXPAND', '是否展开', '下拉框', 'select ''Y'' value,1 code,''是'' name from dual
 union
 select ''N'' value,1 code,''否'' name from dual', null, 'Y', '2', 'Y', null, null, '"Y"', null, '5', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM_GROUP'), 'TEMPLETID', '所属模板ID', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '6', '145', '150', 'Y', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM_GROUP'), 'SEQ', '显示顺序', '数字框', null, null, 'Y', '2', 'Y', null, null, '1000', null, '3', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
  commit;
END;
/
-- ================end export of [T_PUB_TEMPLET_1_ITEM_GROUP]=============================================================

-- 模板生成脚本[T_PUB_TEMPLET_1]
-- ================start===========================================================
-- 删除模板明细数据
delete pub_templet_1_item where pk_pub_templet_1 in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_PUB_TEMPLET_1');
-- 删除模板分组信息
delete from PUB_TEMPLET_1_ITEM_GROUP where templetid in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_PUB_TEMPLET_1');
-- 判断是否已经存在模板
DECLARE TEMPL_COUNT NUMBER(6);
BEGIN
  SELECT COUNT(*) INTO TEMPL_COUNT FROM pub_templet_1 where templetcode ='T_PUB_TEMPLET_1';
  IF TEMPL_COUNT > 0 THEN
    -- 更新老的模板，ID没有变化
    UPDATE PUB_TEMPLET_1 SET  templetcode='T_PUB_TEMPLET_1', templetname='元原模板', tablename='PUB_TEMPLET_1', datasourcename='datasource_default', pkname='PK_PUB_TEMPLET_1', pksequencename='S_PUB_TEMPLET_1', savedtablename='PUB_TEMPLET_1', cardcustpanel='SMARTX', listcustpanel=null, dataconstraint=null, parent_pub_template=null, comefrom='0', ordersetting=null WHERE templetcode = 'T_PUB_TEMPLET_1';
  ELSE
    -- 插入新模板，新生成ID
    Insert Into PUB_TEMPLET_1 (pk_pub_templet_1, templetcode, templetname, tablename, datasourcename, pkname, pksequencename, savedtablename, cardcustpanel, listcustpanel, dataconstraint, parent_pub_template, comefrom, ordersetting) values (s_pub_templet_1.nextval, 'T_PUB_TEMPLET_1', '元原模板', 'PUB_TEMPLET_1', 'datasource_default', 'PK_PUB_TEMPLET_1', 'S_PUB_TEMPLET_1', 'PUB_TEMPLET_1', 'SMARTX', null, null, null, '0', null);
  END IF;
  -- 插入模板分组
 -- 插入模板明细
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'DATACONSTRAINT', '数据过滤条件', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '9', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'ORDERSETTING', '默认排序设定', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '10', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'TEMPLETCODE', '模板编码', '文本框', null, null, 'Y', '1', 'N', null, null, null, null, '2', '180', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'TABLENAME', '查询数据的表名', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '5', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'PKNAME', '主键名', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '7', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'SAVEDTABLENAME', '保存的表名', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '6', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'LISTCUSTPANEL', '列表自定义面板', '文本框', null, null, 'N', '2', 'N', null, null, null, null, '11', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'PARENT_PUB_TEMPLATE', 'PARENT_PUB_TEMPLATE', '数字框', null, null, 'N', '2', 'N', null, null, null, null, '12', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'PK_PUB_TEMPLET_1', '主键', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '1', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'TEMPLETNAME', '模板名称', '文本框', null, null, 'Y', '1', 'N', null, null, null, null, '3', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'DATASOURCENAME', '数据源名称', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '4', '150', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'PKSEQUENCENAME', '主键序列名', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '8', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'CARDCUSTPANEL', '标签', '文本框', null, null, 'Y', '1', 'N', null, null, null, null, '13', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1'), 'COMEFROM', '来源', '下拉框', 'select 0 value#,'''' code#,''系统'' name from dual
union
select 1 value#,'''' code#,''用户'' name from dual', null, 'Y', '2', 'N', null, null, '0', null, '14', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
  commit;
END;
/
-- ================end export of [T_PUB_TEMPLET_1]=============================================================


-- 模板生成脚本[T_PUB_TEMPLET_1_ITEM]
-- ================start===========================================================
-- 删除模板明细数据
delete pub_templet_1_item where pk_pub_templet_1 in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_PUB_TEMPLET_1_ITEM');
-- 删除模板分组信息
delete from PUB_TEMPLET_1_ITEM_GROUP where templetid in (select pk_pub_templet_1 from pub_templet_1 where templetcode = 'T_PUB_TEMPLET_1_ITEM');
-- 判断是否已经存在模板
DECLARE TEMPL_COUNT NUMBER(6);
BEGIN
  SELECT COUNT(*) INTO TEMPL_COUNT FROM pub_templet_1 where templetcode ='T_PUB_TEMPLET_1_ITEM';
  IF TEMPL_COUNT > 0 THEN
    -- 更新老的模板，ID没有变化
    UPDATE PUB_TEMPLET_1 SET  templetcode='T_PUB_TEMPLET_1_ITEM', templetname='元原模板项', tablename='V_PUB_Templetitem', datasourcename='datasource_default', pkname='PK_PUB_TEMPLET_1_ITEM', pksequencename='S_PUB_TEMPLET_1_ITEM', savedtablename='PUB_TEMPLET_1_ITEM', cardcustpanel='SMARTX', listcustpanel=null, dataconstraint=null, parent_pub_template=null, comefrom='0', ordersetting=null WHERE templetcode = 'T_PUB_TEMPLET_1_ITEM';
  ELSE
    -- 插入新模板，新生成ID
    Insert Into PUB_TEMPLET_1 (pk_pub_templet_1, templetcode, templetname, tablename, datasourcename, pkname, pksequencename, savedtablename, cardcustpanel, listcustpanel, dataconstraint, parent_pub_template, comefrom, ordersetting) values (s_pub_templet_1.nextval, 'T_PUB_TEMPLET_1_ITEM', '元原模板项', 'V_PUB_Templetitem', 'datasource_default', 'PK_PUB_TEMPLET_1_ITEM', 'S_PUB_TEMPLET_1_ITEM', 'PUB_TEMPLET_1_ITEM', 'SMARTX', null, null, null, '0', null);
  END IF;
  -- 插入模板分组
 -- 插入模板明细
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'CLIENTREFDESC', '参照客户端说明', '公式', null, null, 'Y', '2', 'N', null, null, null, null, '15', '170', '170', 'Y', '1', 'Y', '1', null, null, null, null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'ISSAVE', '是否参与保存', '下拉框', 'select ''Y'' value,1 code,''是'' name from dual
 union
 select ''N'' value,1 code,''否'' name from dual', null, 'Y', '2', 'Y', null, null, '"Y"', null, '4', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'ITEMKEY', '字段名', '文本框', null, null, 'Y', '2', 'Y', null, null, null, null, '1', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'EDITFORMULA', '编辑公式', '文本框', null, null, 'N', '2', 'N', null, null, null, null, '29', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'COLORFORMULA', '颜色公式', '公式', null, null, 'Y', '2', 'N', null, null, null, null, '30', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'LISTWIDTH', '列表宽度', '数字框', null, null, 'Y', '2', 'Y', null, null, '120', null, '8', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'LISTISSHOWABLE', '列表时是否可显示', '下拉框', 'select ''Y'' value,1 code,''是'' name from dual  union  select ''N'' value,1 code,''否'' name from dual', null, 'Y', '2', 'Y', null, null, '"Y"', null, '9', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'EXTATTR01', '多行文本框高度', '数字框', null, null, 'Y', '3', 'N', null, null, null, null, '31', '200', '200', 'N', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'EXTATTR04', '虚拟列内容', '文本框', null, null, 'Y', '3', 'N', null, null, null, null, '35', '200', '200', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'CARDISSHOWABLE', '卡片时是否可显示', '下拉框', 'select ''Y'' value,1 code,''是'' name from dual  union  select ''N'' value,1 code,''否'' name from dual', null, 'Y', '2', 'Y', null, null, '"Y"', null, '12', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'BCOLORFORMULA', '背景色公式处理', '文本框', null, null, 'N', '2', 'N', null, null, null, null, '23', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'CARDISEDITABLE', '卡片时是否可编辑', '下拉框', 'select 1 value,1 code,''全部可编辑'' name from dual
  union
  select 2 value,1 code,''仅新增可编辑'' name from dual
  union
  select 3 value,1 code,''仅修改可编辑'' name from dual
  union
  select 4 value,1 code,''全部禁用'' name from dual', null, 'Y', '2', 'Y', null, null, '1', null, '13', '180', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'ITEMACTION', '字段触发器处理', '文本框', null, null, 'N', '2', 'N', null, null, null, null, '25', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'DEFAULTCONDITION', '条件默认值公式', '文本框', null, null, 'N', '2', 'N', null, null, null, null, '26', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'CONDITION_COMBOXDESC', '条件下拉框', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '19', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'CONDITION_SHOWORDER', '条件顺序', '数字框', null, null, 'N', '2', 'N', null, null, null, null, '27', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'PK_PUB_TEMPLET_1', '父表主键', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '28', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'ITEMNAME', '显示名称', '文本框', null, null, 'Y', '2', 'Y', null, null, null, null, '2', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'COMBOXDESC', '下拉框说明', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '16', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'PK_PUB_TEMPLET_1_ITEM', '主键', '数字框', null, null, 'Y', '2', 'N', null, null, null, null, '22', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'ITEMTYPE', '控件类型', '下拉框', 'select * from (
select ''文本框'' value,1 code,''文本框'' name from dual
union
select ''数字框'' value,2 code,''数字框'' name from dual
union
select ''下拉框'' value,3 code,''下拉框'' name from dual
union
select ''参照'' value,4 code,''参照'' name from dual
union
select ''时间'' value,5 code,''时间'' name from dual
union
select ''日历'' value,6 code,''日历'' name from dual
union
select ''多行文本框'' value,7 code,''多行文本框'' name from dual
union
select ''公式'' value,8 code,''公式'' name from dual
union
select ''密码框'' value,9 code,''密码框'' name from dual
union
select ''自动填充文本框'' value,10 code,''自动填充文本框'' name from dual
union
select ''列表框'' value,11 code,''列表框'' name from dual
) order by code ', null, 'Y', '2', 'Y', null, null, '"文本框"', null, '3', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'REFDESC', '参照说明', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '14', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'ISDEFAULTQUERY', '默认查询条件', '下拉框', 'select 1 value,1 code,''快速查询'' name from dual
 union
select 2 value,1 code,''高级查询'' name from dual
 union
 select 3 value,1 code,''禁止查询'' name from dual', null, 'Y', '2', 'Y', null, null, '3', null, '6', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'LOADFORMULA', '加载/显示公式', '文本框', null, null, 'N', '2', 'N', null, null, null, null, '24', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'DEFAULTVALUEFORMULA', '默认值公式', '公式', null, null, 'Y', '2', 'N', null, null, null, null, '21', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'SHOWORDER', '显示顺序', '数字框', null, null, 'Y', '2', 'Y', null, null, '1000', null, '7', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'CARDWIDTH', '卡片宽度', '数字框', null, null, 'Y', '2', 'Y', null, null, '150', null, '11', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'LISTISEDITABLE', '列表时是否可编辑', '下拉框', 'select 1 value,1 code,''全部可编辑'' name from dual
  union
  select 2 value,1 code,''仅新增可编辑'' name from dual
  union
  select 3 value,1 code,''仅修改可编辑'' name from dual
  union
  select 4 value,1 code,''全部禁用'' name from dual', null, 'Y', '2', 'Y', null, null, '1', null, '10', '180', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'ISMUSTINPUT', '是否必输项', '下拉框', 'select ''Y'' value,1 code,''是'' name from dual  union  select ''N'' value,1 code,''否'' name from dual', null, 'Y', '2', 'Y', null, null, '"N"', null, '5', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'CONDITION_ITEMTYPE', '条件控件类型', '下拉框', 'select * from (
select ''文本框'' value,1 code,''文本框'' name from dual
union
select ''数字框'' value,2 code,''数字框'' name from dual
union
select ''下拉框'' value,3 code,''下拉框'' name from dual
union
select ''参照'' value,4 code,''参照'' name from dual
union
select ''时间'' value,5 code,''时间'' name from dual
union
select ''日历'' value,6 code,''日历'' name from dual
union
select ''密码框'' value,9 code,''密码框'' name from dual
union
select ''日期范围'' value,11 code,''日期范围'' name from dual
union
select ''数值范围'' value,12 code,''数值范围'' name from dual
union
select ''自定义控件'' value,900 code,''自定义控件'' name from dual
) order by code ', null, 'Y', '2', 'N', null, null, null, null, '18', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'CONDITION_REFDESC', '条件参照', '文本框', null, null, 'Y', '2', 'N', null, null, null, null, '20', '145', '150', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'EXTATTR05', '联动条件语句', '多行文本框', null, null, 'Y', '3', 'N', null, null, null, null, '36', '200', '200', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'TEMPLETITEMGROUPID', '所属分组', '参照', 'select id,1,name from PUB_TEMPLET_1_ITEM_GROUP where 1=1', 'select id,1,name from PUB_TEMPLET_1_ITEM_GROUP where 1=1', 'Y', '3', 'N', null, null, null, null, '32', '200', '200', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, '"select id id#,1 code#,name 分组名 from PUB_TEMPLET_1_ITEM_GROUP where 1=1 and templetid="+sysGetVar("PK_PUB_TEMPLET_1")', null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'EXTATTR02', '是否是虚拟列', '下拉框', 'select ''Y'' value,1 code,''是'' name from dual
 union
 select ''N'' value,1 code,''否'' name from dual', null, 'Y', '3', 'N', null, null, '"N"', null, '33', '200', '200', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'EXTATTR03', '虚拟列类型', '下拉框', 'select 0 as id,''value'' as code,''数值'' as name from dual
union
select 1 as id,''famula'' as code,''公式'' as name from dual
union
select 2 as id,''javaclass'' as code,''JAVA实现类'' as name from dual', null, 'Y', '3', 'N', null, null, null, null, '34', '200', '200', 'Y', '1', 'Y', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
 Insert Into pub_templet_1_item (pk_pub_templet_1_item, pk_pub_templet_1, itemkey, itemname, itemtype, comboxdesc, refdesc, issave, isdefaultquery, ismustinput, loadformula, editformula, defaultvalueformula, colorformula, showorder, listwidth, cardwidth, listisshowable, listiseditable, cardisshowable, cardiseditable, bcolorformula, itemaction, ismustcondition, defaultcondition, condition_itemtype, condition_comboxdesc, condition_refdesc, condition_showorder, templetitemgroupid, clientrefdesc, extattr01, extattr02, extattr03, extattr04, extattr05, extattr06, extattr07, extattr08, extattr09, extattr10) values (s_pub_templet_1_item.nextval, (select PK_PUB_TEMPLET_1  From pub_templet_1 Where TEMPLETCODE = 'T_PUB_TEMPLET_1_ITEM'), 'ISMUSTCONDITION', '是否必输条件', '下拉框', 'select ''Y'' value,1 code,''是'' name from dual  union  select ''N'' value,1 code,''否'' name from dual', null, 'Y', '2', 'N', null, null, '"N"', null, '17', '145', '150', 'N', '1', 'N', '1', null, null, 'N', null, null, null, null, null,null, null, null, 'N', null, null, null, null, null, null, null, null);
  commit;
END;
/
-- ================end export of [T_PUB_TEMPLET_1_ITEM]=============================================================
